FROM docker.io/library/alpine:3.22

LABEL org.opencontainers.image.source "https://git.cubieserver.de/Cubieserver/homelab"
LABEL org.opencontainers.image.title "Toolbox for Jack's Homelab"

# Install tools and dependencies
RUN apk add --no-cache \
    bash \
    git \
    nano \
    kubectl \
    helm \
    kustomize \
    curl \
    sops \
    jq \
    xz \
    gzip \
    bzip2 \
    zstd \
    coreutils \
    tcpdump \
    strace \
    ca-certificates

ENV YQ_VERSION=4.47.2
RUN cd /tmp \
    && curl -LO "https://github.com/mikefarah/yq/releases/download/v${YQ_VERSION}/yq_linux_amd64.tar.gz" \
    && tar -xzf yq_linux_amd64.tar.gz \
    && chmod +x yq_linux_amd64 \
    && mv yq_linux_amd64 /usr/local/bin/yq \
    && rm -rf /tmp/*

# Install Helmfile (not available in alpine stable repo)
ENV HELMFILE_VERSION=1.1.7
RUN cd /tmp \
    && curl -LO "https://github.com/helmfile/helmfile/releases/download/v${HELMFILE_VERSION}/helmfile_${HELMFILE_VERSION}_linux_amd64.tar.gz" \
    && tar -xzf helmfile_${HELMFILE_VERSION}_linux_amd64.tar.gz \
    && chmod +x helmfile \
    && mv helmfile /usr/local/bin/ \
    && rm -rf /tmp/*

# Install additional Helm plugins
# https://github.com/databus23/helm-diff/releases
RUN helm plugin install https://github.com/databus23/helm-diff --version v3.12.4
# https://github.com/jkroepke/helm-secrets/releases
RUN helm plugin install https://github.com/jkroepke/helm-secrets --version v4.6.5

# Install kubedump
# https://github.com/sj14/kubedump/releases
ENV KUBEDUMP_VERSION=0.8.2
RUN cd /tmp \
    && curl -LO "https://github.com/sj14/kubedump/releases/download/v${KUBEDUMP_VERSION}/kubedump_${KUBEDUMP_VERSION}_linux_amd64" \
    && mv "kubedump_${KUBEDUMP_VERSION}_linux_amd64" /usr/local/bin/kubedump \
    && chmod +x /usr/local/bin/kubedump

# Set working directory
WORKDIR /workspace
