apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: homepage
spec:
  interval: 5m
  chart:
    spec:
      # https://github.com/jameswynn/helm-charts/tree/main/charts/homepage
      chart: "homepage"
      version: "1.1.0"
      sourceRef:
        kind: HelmRepository
        name: jameswynn

  # https://github.com/jameswynn/helm-charts/blob/main/charts/homepage/values.yaml
  values:
    image:
      # https://github.com/benphelps/homepage/releases
      repository: ghcr.io/benphelps/homepage
      tag: v0.6.10
    enableRbac: true
    serviceAccount:
      create: true
    resources:
      requests:
        memory: 80Mi
        cpu: 10m
      limits:
        memory: 250Mi
        cpu: 200m

    # Note: ingress should be defined in the Kustomize overlay!
    ingress: {}

    # config files passed to homepage application
    # https://gethomepage.dev/en/configs/services/
    config:
      # https://gethomepage.dev/en/configs/kubernetes/
      kubernetes:
        mode: cluster # use serviceaccount from container

      # https://gethomepage.dev/en/configs/settings
      settings:
        title: "Cubieserver.de - Jack's Homelab"

        # https://unsplash.com/photos/XKEObIMh0V0
        background: "https://images.unsplash.com/photo-1506781994843-d2c500b1dde1?auto=format&fit=crop&w=2560&q=80"
        backgroundOpacity: 0.4
        color: zinc

        headerStyle: boxed

        hideVersion: true

      # https://gethomepage.dev/en/configs/bookmarks
      bookmarks:
        - Links:
          - "Jack's Blog":
            - abbr: JH
              href: https://blog.cubieserver.de
          - "Homelab Git repository":
            - abbr: HL
              href: https://git.cubieserver.de/cubieserver/homelab
          - "Status Page":
            - abbr: SP
              href: https://status.cubieserver.de

      # https://gethomepage.dev/en/configs/services
      # Icons from https://github.com/walkxcode/dashboard-icons and https://github.com/walkxcode/dashboard-icons are supported
      services:
        - "Web services":
            - Nextcloud:
                href: https://cloud.cubieserver.de
                icon: nextcloud.png
                description: Platform for online file sharing, pictures, contacts, calendar and more
                namespace: nextcloud
                app: nextcloud
            - Authentik:
                href: https://auth.cubieserver.de
                icon: authentik-orange.png
                description: Account management & Authentication
                namespace: authentik
                app: authentik
            - Woodpecker:
                href: https://ci.cubieserver.de
                icon: mdi-disc
                description: CI/CD service
                namespace: nextcloud
                app: nextcloud
            - Gitea:
                href: https://git.cubieserver.de
                icon: gitea.png
                description: Git repository service
                namespace: gitea
                app: gitea
            - Jellyfin:
                href: http://192.168.1.10:8096
                icon: jellyfin.png
                description: Media server
                namespace: jellyfin
                app: jellyfin

        - "Backend services":
            - ejabberd:
                icon: mdi-xmpp
                description: XMPP messaging server
                namespace: ejabberd
                app: ejabberd
            - Minio:
                href: https://console-s3.cubieserver.de
                icon: minio.png
                description: S3 blob storage
                namespace: minio
                app: minio
            - Traefik:
                icon: traefik.png
                description: HTTP proxy and router
                namespace: traefik
                app: traefik
            - PostgreSQL:
                icon: postgres.png
                description: Postgres relational database
                namespace: postgres
                app: postgresql
            - MariaDB:
                icon: mariadb.png
                description: MySQL-compatible SQL database
                namespace: mariadb
                app: mariadb
            - k3s:
                icon: https://k3s.io/img/k3s-logo-light.svg
                description: Kubernetes cluster



      # https://gethomepage.dev/en/configs/widgets
      widgets:
        - logo:
            icon: https://blog.cubieserver.de/images/wheel.jpg

        - greeting:
            text_size: 2xl
            text: "Jack's Homelab"

        - search:
            provider: duckduckgo
            target: _self

        # show the kubernetes widget, with the cluster summary and individual nodes
        - kubernetes:
            cluster:
              show: true
              cpu: true
              memory: true
              showLabel: false
              label: "cluster"
            nodes:
              show: false
              cpu: false
              memory: false
              showLabel: false
