apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitea
spec:
  interval: 5m
  chart:
    spec:
      # https://gitea.com/gitea/helm-chart
      # https://gitea.com/gitea/helm-chart#upgrading
      # https://gitea.com/gitea/helm-chart/releases
      chart: "gitea"
      version: "8.2.0" # was: 5.0.0
      sourceRef:
        kind: HelmRepository
        name: gitea

  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1

  # https://gitea.com/gitea/helm-chart/src/branch/main/values.yaml
  values:
    image:
      tag: "1.17.2"
      pullPolicy: IfNotPresent
      rootless: true
    gitea:
      admin:
        existingSecret: "gitea-admin-credentials" # Secret created in overlay

      # Gitea configuration, aka. gitea.ini
      # https://docs.gitea.io/en-us/config-cheat-sheet/
      config:
        APP_NAME: 'Gitea: Git@Cubieserver'
        server:
          SSH_PORT: 2222
          DOMAIN: "" # set via overlay
          # SSH_DOMAIN: "%(DOMAIN)"
          # ROOT_URL: "https://%(DOMAIN)"
          OFFLINE_MODE: true
          LANDING_PAGE: "explore"
        service:
          # registrations needs to be enabled so new users can join via OIDC
          DISABLE_REGISTRATION: false
          # users should register themselves with the IDP, not in Gitea
          SHOW_REGISTRATION_BUTTON: false
        log:
          LEVEL: "Info" # Trace, Debug, Info, Warn, Error, Critical, Fatal, None
          DISABLE_ROUTER_LOG: true # disable noisy HTTP access logs

        picture:
          DISABLE_GRAVATAR: true

      # https://docs.gitea.io/en-us/administration/config-cheat-sheet/#database-database
      additionalConfigFromEnvs:
        # gitea-db-credentials is created from database.yaml
        - name: ENV_TO_INI__DATABASE__DB_TYPE
          value: "mysql"
        - name: ENV_TO_INI__DATABASE__LOG_SQL
          value: "false"
        - name: ENV_TO_INI__DATABASE__HOST
          valueFrom:
            secretKeyRef:
              name: gitea-db-credentials
              key: host
        - name: ENV_TO_INI__DATABASE__NAME
          valueFrom:
            secretKeyRef:
              name: gitea-db-credentials
              key: name
        - name: ENV_TO_INI__DATABASE__USER
          valueFrom:
            secretKeyRef:
              name: gitea-db-credentials
              key: user
        - name: ENV_TO_INI__DATABASE__PASSWD
          valueFrom:
            secretKeyRef:
              name: gitea-db-credentials
              key: password

    persistence:
      enabled: true
      # deploying Gitea with local storage because the Helm chart uses a StatefulSet anyway,
      # meaning the pod cannot be re-scheduled onto another node
      storageClass: "local-path"
      size: 10Gi

    resources:
      requests:
        memory: 128Mi
        cpu: 50m
      limits:
        memory: 512Mi

    service:
      ssh:
        port: 2222 # see SSH_PORT above

    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      # set via overlay:
      # hosts: []
      # tls: []

    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      privileged: false
      readOnlyRootFilesystem: true
      runAsGroup: 1000
      runAsUser: 1000

    podSecurityContext:
      fsGroup: 1000
      runAsNonRoot: true

    # disabled unwanted dependencies
    memcached:
      enabled: false
    postgresql:
      enabled: false
    test:
      enabled: false

  valuesFrom:
    - kind: Secret
      name: secret-helm-values # created in overlay
