config:
    general:
        RELAYHOST: ENC[AES256_GCM,data:1Uvyk3XY/PmtWCQtzn0QG9o=,iv:dOApL+30hj4hkdRuJgtYfroOAQAzWXWyiCXp2ND0vt4=,tag:UUk12ZDySA+TphfbI+FGig==,type:str]
        RELAYHOST_USERNAME: ENC[AES256_GCM,data:0BGT5U1J5k73rPtihHtFR4rbl/E=,iv:8gi5J5OD3maIgfneKWHb+zepBIm/yRgq3SWizc+Pd3Q=,tag:vcS49naZu5yDjXZqsuBgFg==,type:str]
        RELAYHOST_PASSWORD: ENC[AES256_GCM,data:O/C50ejYeh+o9b3EKONL+yDnQH5L,iv:MUt4+TGMXRfLrncorDZw64r0bejCvhhu+OduTlVsxYM=,tag:OQ/WgOzL9EE+zlv5UPBirQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lk9rqgq9kls8u08vadgc8pq2vwamrjkgzn3ekvthlmfffh4akflsauata6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBac3pnS3dLbEp6Y3VDMzRk
            bmFCK2JPZW9NSWEzVmZjbkN1NDczTVhvWDF3CnpoVTEvbG85ck9LTmNaMUVuQm5N
            Ui9FV25rZHdreGtZbi8vaVdnNkw0b2MKLS0tIDVCWWl5RUF5WkNCd292aktXU1dI
            QzdRYXNmVVZ4S0dOOTdoZ2U2V21ub00K5UTwqnDt//qBIWpQj6bkG0ti0KciaAor
            M9xCv3+8+8ie6Bq4urpZG8KIruIEsoGFqnVoIqbuTRJAryB9b+6cUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-06T12:55:00Z"
    mac: ENC[AES256_GCM,data:BSrcqtP8vN1RxfCEJbi1AWzVhU68XaawX4c4OrTrd3Zqa3TkaEe+QsseIWiSpuZ9lbuzaI3vHzpl+mp3ubDvqATuU7F4PoFbxgDLQbZ0pwrhx5Wnieyaxj5t6hlv58B7JYFptUvT5LMByqG17e8IKuKA7ZAS2F+WuiCADpQ7rIA=,iv:k1FKyIX+0q5oYnZ56IodHUyJ9FueGDHCAWWGqSY3RLY=,tag:sNEqPdr2ieye87VMj1hZBQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
