apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: juicefs-csi
spec:
  interval: 1m
  chart:
    spec:
      chart: juicefs-csi-driver
      version: 0.13.5 # appVersion: 0.17.5
      sourceRef:
        kind: HelmRepository
        name: juicedata
  # https://github.com/juicedata/charts/blob/main/charts/juicefs-csi-driver/values.yaml
  values:
    controller:
      enabled: true
      # enable automatic provisioning of volumes / buckets
      # https://juicefs.com/docs/csi/introduction#dynamic-provisioning
      provisioner: true
    # Note: the storageClasses section is defined in a secret
  valuesFrom:
    - kind: Secret
      name: juicefs-values
      valuesKey: values.yaml
