# Redis is the Metadata store for JuiceFS
# https://juicefs.com/docs/community/databases_for_metadata#redis
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis-metadata
spec:
  interval: 1m
  chart:
    spec:
      chart: redis
      version: 16.13.2 # appVersion: 6.2.7
      sourceRef:
        kind: HelmRepository
        name: bitnami
  # https://github.com/bitnami/charts/blob/main/bitnami/redis/values.yaml
  values:
    architecture: standalone
    commonConfiguration: |-
      # Enable AOF https://redis.io/topics/persistence#append-only-file
      appendonly yes
      # Take snapshots every hour if at least 1 key changed (in addition to AOF, for backups)
      # https://redis.io/docs/management/persistence/#snapshotting
      save 3600 1
    master:
      persistence:
        storageClass: "local-path"
  valuesFrom:
    - kind: Secret
      name: juicefs-values
      valuesKey: redisPassword
      targetPath: auth.password
