repositories:
 - name: prometheus-community
   url: https://prometheus-community.github.io/helm-charts
 - name: gitea
   url: https://dl.gitea.io/charts/
 - name: incubator
   url: https://charts.helm.sh/incubator
 - name: jameswynn
   url: https://jameswynn.github.io/helm-charts
 - name: bitnamicharts-oci
   url: docker.io/bitnamicharts
   oci: true
 - name: authentik
   url: https://charts.goauthentik.io/
 - name: nextcloud
   url: https://nextcloud.github.io/helm/
 - name: stirling-tools
   url: https://stirling-tools.github.io/Stirling-PDF-chart
 - name: pajikos
   url: https://pajikos.github.io/home-assistant-helm-chart/
 - name: traefik
   url: https://helm.traefik.io/traefik
   # https://github.com/bjw-s-labs/helm-charts
 - name: bjw-s
   url: https://bjw-s-labs.github.io/helm-charts
 - name: jetstack
   url: https://charts.jetstack.io
 - name: db-operator
   url: https://db-operator.github.io/charts
 - name: jellyfin
   url: https://jellyfin.github.io/jellyfin-helm
 - name: docker-postfix
   url: https://bokysan.github.io/docker-postfix/
 - name: martialblog
   url: https://martialblog.github.io/helm-charts

  # - name: myOCIRegistry
  #   url: myregistry.azurecr.io
  #   oci: true

---

# for database-like workloads, use XFS partition instead of btrfs
# Due to the Copy-on-Write concept, btrfs volumes are not well suited for workloads
# that frequently update their own files, e.g. databases.
# While CoW can be manually disabled for specific file and directories, this introduces
# additional operational overhead.
# https://wiki.archlinux.org/title/Btrfs#Disabling_CoW
# Thus, the production system has a separate xfs partition

helmDefaults:
  historyMax: 3

kubeVersion: v1.30

releases:
- name: storage
  chart: ./storage
  namespace: kube-system

# TODO: also manage backup cronjob with Helmfile
- name: mariadb
  chart: bitnamicharts-oci/mariadb
  version: 20.1.1
  namespace: mariadb
  createNamespace: true
  labels:
    type: platform
  secrets:
    - ./mariadb/mariadb-values.secret.yaml
  values:
    - ./mariadb/values.yaml

# - name: kub-vol-bak
#   chart: ./kub-vol-bak
#   namespace: kub-vol-bak
#   createNamespace: true
#   condition: backup.enabled
#   secrets:
#     - "./environments/{{ .Environment.Name }}/kub-vol-bak.secret.yaml"

# helm upgrade --install kube-prometheus-stack -n monitoring -f monitoring/kube-prometheus-stack.values.yaml prometheus-community/kube-prometheus-stack
- name: kube-prometheus-stack
  namespace: monitoring
  createNamespace: true
  labels:
    type: platform
  version: 77.1.0
  chart: prometheus-community/kube-prometheus-stack
  values:
  - monitoring/kube-prometheus-stack.values.yaml

- name: traefik
  namespace: traefik
  createNamespace: true
  labels:
    type: platform
  # https://github.com/traefik/traefik-helm-chart/tags
  version: 37.0.0
  chart: traefik/traefik
  values:
  - traefik/traefik.values.yaml
  # Traefik UI can be accessed at <http://localhost:9000/dashboard/> after running:
  # kubectl -n traefik port-forward $(kubectl -n traefik get pods --selector "app.kubernetes.io/name=traefik" --output=name) 9000:9000

# helm upgrade --install prometheus-adapter -n monitoring -f monitoring/prometheus-adapter.values.yaml prometheus-community/prometheus-adapter
- name: prometheus-adapter
  namespace: monitoring
  labels:
    type: platform
  # https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-adapter/Chart.yaml
  # https://github.com/kubernetes-sigs/prometheus-adapter/releases
  version: 5.1.0
  chart: prometheus-community/prometheus-adapter
  values:
  - monitoring/prometheus-adapter.values.yaml

- name: cert-manager
  namespace: cert-manager
  createNamespace: true
  labels:
    type: platform
  # https://github.com/cert-manager/cert-manager/releases
  chart: jetstack/cert-manager
  version: v1.17.1
  values:
    - ./cert-manager/values.yaml

- name: db-operator
  namespace: db-operator
  labels:
    type: platform
  chart: db-operator/db-operator
  version: 1.41.0
  values:
    - ./db-operator/values.yaml

# Note: we cannot use the `extraDeploy` value of the Gitea Helm chart for this resource,
# because the Gitea Helm chart runs a Helm template over the value, which means we loose the
# curly brackets (that should remain as is so they are passed to the DB operator).
- name: gitea-extras
  namespace: gitea
  labels:
    type: app
  chart: incubator/raw
  version: 0.2.5
  values:
    - ./gitea-extras/values.yaml

- name: gitea
  namespace: gitea
  createNamespace: true
  labels:
    type: app
  # https://gitea.com/gitea/helm-chart
  # https://gitea.com/gitea/helm-chart#upgrading
  # https://gitea.com/gitea/helm-chart/releases
  chart: gitea/gitea
  version: 10.5.0
  secrets:
    - gitea/gitea-values.secret.yaml
  values:
    - gitea/values.yaml
  postRenderer: "./gitea/post-render.sh"

- name: s3-website-gateway
  namespace: static-websites
  createNamespace: true
  labels:
    type: app
  chart: ./s3-website-gateway/chart/
  values:
    - s3-website-gateway/cubieserver.yaml

  # Deploys an instance of https://github.com/gethomepage/homepage (https://github.com/gethomepage/homepage)
- name: homepage
  namespace: homepage
  createNamespace: true
  labels:
    type: app
  chart: jameswynn/homepage # unofficial helm chart: https://github.com/jameswynn/helm-charts/tree/main/charts/homepage
  version: 2.1.0
  values:
    - homepage/values.yaml

- name: postgres
  namespace: postgres
  createNamespace: true
  labels:
    type: platform
  chart: bitnamicharts-oci/postgresql
  version: 16.7.27
  secrets:
    - postgres/postgres-values.secret.yaml
  values:
    - postgres/values.yaml

- name: authentik
  namespace: authentik
  createNamespace: true
  labels:
    type: app
  # https://github.com/goauthentik/authentik/releases
  # https://goauthentik.io/docs/releases
  # https://github.com/goauthentik/helm
  # note 1: Authentik releases and Helm chart releases are in-sync
  # note 2: Authentik does NOT support skipping releases
  chart: authentik/authentik
  version: "2025.8.4"
  secrets:
    - authentik/authentik-values.secret.yaml
  values:
    - authentik/values.yaml

- name: authentik-extras
  namespace: authentik
  labels:
    type: app
  chart: incubator/raw
  version: 0.2.5
  values:
    - authentik/authentik-extras-values.yaml

- name: nextcloud
  namespace: nextcloud
  createNamespace: true
  labels:
    type: app
  # https://github.com/nextcloud/helm/tree/main/charts/nextcloud
  chart: nextcloud/nextcloud
  version: 6.6.10
  secrets:
    - nextcloud/nextcloud-values.secret.yaml
  values:
    - nextcloud/values.yaml

- name: nextcloud-extras
  namespace: nextcloud
  labels:
    type: app
  chart: incubator/raw
  version: 0.2.5
  values:
  - nextcloud/nextcloud-extras.yaml

- name: stirling-pdf
  namespace: stirling-pdf
  createNamespace: true
  labels:
    type: app
  chart: stirling-tools/stirling-pdf-chart
  version: 2.2.0
  values:
    - stirling-pdf/values.yaml

  # Note: for initial setup, follow: https://www.home-assistant.io/getting-started/onboarding/
- name: home-assistant
  namespace: home-assistant
  createNamespace: true
  labels:
    type: app
  chart: pajikos/home-assistant
  version: 0.2.24
  values:
    - home-assistant/values.yaml

- name: redlib
  namespace: reddit
  createNamespace: true
  labels:
    type: app
  chart: ./redlib/chart/
  values:
    - redlib/values.yaml

- name: jellyfin
  namespace: jellyfin
  createNamespace: true
  labels:
    type: app
  chart: jellyfin/jellyfin
  version: 2.3.0
  values:
    - jellyfin/jellyfin.values.yaml

- name: arr
  namespace: jellyfin
  labels:
    type: app
  chart: bjw-s/app-template
  version: "3.7.3"
  values:
    - jellyfin/arr.values.yaml

- name: webtools
  namespace: webtools
  createNamespace: true
  labels:
    type: app
  chart: bjw-s/app-template
  version: "3.7.3"
  values:
    - webtools/values.yaml

# - name: ejabberd
#   namespace: ejabberd
#   labels:
#     type: app
#   chart: martialblog/ejabberd
#   version: "0.3.0"
#   secrets:
#     - ejabberd/ejabberd-values.secret.yaml
#   values:
#     - ejabberd/values.yaml

- name: olivetin
  namespace: olivetin
  createNamespace: true
  labels:
    type: app
  chart: bjw-s/app-template
  version: "3.7.3"
  values:
    - olivetin/olivetin.values.yaml

- name: postfix
  namespace: postfix
  createNamespace: true
  labels:
    type: platform
  chart: docker-postfix/mail
  version: 4.4.0
  secrets:
    - postfix/postfix-values.secret.yaml
  values:
    - postfix/values.yaml
