apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebrowser
  labels:
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/component: filebrowser
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: jellyfin
      app.kubernetes.io/component: filebrowser
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jellyfin
        app.kubernetes.io/component: filebrowser
    spec:
      containers:
        # https://github.com/filebrowser/filebrowser/blob/master/CHANGELOG.md
      - image: docker.io/filebrowser/filebrowser:v2.23.0-s6
        name: filebrowser
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
          hostPort: 8097
        env:
          - name: "FB_NOAUTH"
            value: "true"
        volumeMounts:
          - name: data
            mountPath: /srv
          - name: database
            mountPath: /database
        resources: {}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: jellyfin-data
        - name: database
          emptyDir: {}
