---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: jellyfin
  name: jellyfin
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8096
    protocol: TCP
    targetPort: 8096
  selector:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: jellyfin
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: filebrowser
    app.kubernetes.io/name: jellyfin
  name: filebrowser
spec:
  type: LoadBalancer
  ports:
  - port: 8097
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/component: filebrowser
    app.kubernetes.io/name: jellyfin
