# https://github.com/bitnami/charts/blob/postgresql/13.2.9/bitnami/postgresql/values.yaml
fullnameOverride: "postgres"
image:
  # https://hub.docker.com/r/bitnamilegacy/postgresql/tags
  registry: docker.io
  repository: bitnamilegacy/postgresql
  tag: 14-debian-11
# sleep infinity + disable health probes
# diagnosticMode:
#   enabled: true
auth:
  # postgresPassword set in secret.yaml
serviceAccount:
  create: true
primary:
  service:
    type: ClusterIP
  persistence:
    storageClass: "local-path-xfs"
    size: 1
    annotations:
      # backups are handled via pgdump to be fully consistent
      # (which is not guaranteed with filesystem-level backups)
      backup-enabled: "false"
  resources:
    requests:
      cpu: 250m
      memory: 250Mi
    limits:
      cpu: 1
      memory: 1Gi

extraDeploy:
- apiVersion: kinda.rocks/v1beta1
  kind: DbInstance
  metadata:
    name: pg-instance-prod
    # cluster-wide resource, no namespace
  spec:
    adminSecretRef:
      # TODO: this secret should be managed by Helm as well
      Name: postgres-admin-secret-for-db-instance
      Namespace: postgres
    engine: postgres
    generic:
      host: postgres.postgres.svc.cluster.local
      port: 5432
    monitoring:
      enabled: false
    sslConnection:
      enabled: false
