# https://cert-manager.io/docs/configuration/acme/
# These resources are cluster-scoped, so they don't have a namespace
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: admin@cubieserver.de
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging-account-key
    solvers:
    - http01:
       ingress:
         ingressTemplate:
           metadata:
             annotations:
               kubernetes.io/ingress.class: "" # default ingress controller
               traefik.ingress.kubernetes.io/router.priority: "100"
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    email: admin@cubieserver.de
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-production-account-key
    solvers:
    - http01:
       ingress:
         ingressTemplate:
           metadata:
             annotations:
               kubernetes.io/ingress.class: "" # default ingress controller
               traefik.ingress.kubernetes.io/router.priority: "100"
