apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  interval: 5m
  chart:
    spec:
      chart: "cert-manager"
      version: "v1.7.1"
      sourceRef:
        kind: HelmRepository
        name: jetstack-charts
      interval: 1m
  values:
    installCRDs: true
    resources:
      requests:
        memory: 40Mi
      limits:
        memory: 100Mi
    containerSecurityContext:
      capabilities: { drop: ["ALL"] }
      readOnlyRootFilesystem: true,
      runAsNonRoot: true,
    prometheus:
      enabled: false
    webhook:
      containerSecurityContext:
        capabilities: { drop: ["ALL"] }
        readOnlyRootFilesystem: true,
        runAsNonRoot: true,
      resources:
        requests:
          memory: 20Mi
        limits:
          memory: 100Mi
    cainjector:
      containerSecurityContext:
        capabilities: { drop: ["ALL"] }
        readOnlyRootFilesystem: true,
        runAsNonRoot: true,
      resources:
        requests:
          memory: 40Mi
        limits:
          memory: 100Mi
    startupapicheck:
      enabled: false
