apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: s3-website-gateway
spec:
  interval: 5m
  chart:
    spec:
      chart: "s3-website-gateway"
      reconcileStrategy: Revision
      version: "c94773f"
      sourceRef:
        kind: GitRepository
        name: jacks-helm-charts

  values:
    image:
      tag: "1.25"

    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 1
        memory: 128Mi

    # websites: [] are set separately for each environment
