apiVersion: kci.rocks/v1beta1
kind: Database
metadata:
  name: authentik
spec:
  secretName: authentik-db-credentials
  instance: "" # set via overlay
  deletionProtected: false
  backup:
    enable: false
    cron: "0 0 * * *"
  secretsTemplates:
    # https://goauthentik.io/docs/installation/configuration#postgresql-settings
    AUTHENTIK_POSTGRESQL__HOST: "{{ .DatabaseHost }}"
    AUTHENTIK_POSTGRESQL__NAME: "{{ .DatabaseName }}"
    AUTHENTIK_POSTGRESQL__USER: "{{ .UserName }}"
    AUTHENTIK_POSTGRESQL__PORT: "{{ .DatabasePort }}"
    AUTHENTIK_POSTGRESQL__PASSWORD: "{{ .Password }}"
    AUTHENTIK_POSTGRESQL__USE_PGBOUNCER: "false"
