apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
spec:
  interval: 5m
  chart:
    spec:
      # https://github.com/goauthentik/authentik/releases
      # https://goauthentik.io/docs/releases
      # https://github.com/goauthentik/helm
      # note Authentik releases and Helm chart releases are in-sync
      chart: "authentik"
      version: "2023.4.1"
      sourceRef:
        kind: HelmRepository
        name: authentik

  # After first installation, go to https://INGRESS/if/flow/initial-setup/ to set a password for the admin user.

  # https://github.com/goauthentik/helm/blob/main/charts/authentik/values.yaml
  values:
    serviceAccount:
      create: false
    authentik:
      # https://goauthentik.io/docs/installation/configuration
      avatars: "none"
      log_level: "info" # trace, debug, info, warning, error
      # "secret_key" set from secret-helm-values
      error_reporting:
        enabled: false
      disable_update_check: true
      disable_startup_analytics: true
      postgresql: null # postgres config is set via environment variables

    envFrom:
      - secretRef:
          name: authentik-db-credentials

    livenessProbe:
      enabled: true
      initialDelaySeconds: 60
      periodSeconds: 30

    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      # "hosts" set from secret-helm-values
      # "tls" set from secret-helm-values

    resources:
      server:
        requests:
          memory: 450Mi
          cpu: 10m
        limits:
          memory: 900Mi
      worker:
        requests:
          memory: 250Mi
          cpu: 10m
        limits:
          memory: 500Mi
          cpu: 100m

    # deploy Bitnami's Redis chart as a dependency
    redis:
      enabled: true
      # redis is only used as a cache / queue, no need for persistence
      # disabling persistence uses emptyDir instead
      # https://github.com/bitnami/charts/blob/master/bitnami/redis/README.md
      master:
        persistence:
          enabled: false

    # we deploy our own postgres instance
    poostgresql:
      enabled: false

    # for server
    securityContext:
      runAsNonRoot: true

    # waiting for https://github.com/goauthentik/helm/pull/93
    # podSecurityContext:
    #   allowPrivilegeEscalation: false
    #   capabilities: { drop: ["ALL"] }
    #   readOnlyRootFilesystem: true


    # for worker
    worker:
      securityContext:
        runAsNonRoot: true
      # waiting for https://github.com/goauthentik/helm/pull/93
      # podSecurityContext:
      #   allowPrivilegeEscalation: false
      #   capabilities: { drop: ["ALL"] }
      #   readOnlyRootFilesystem: true

    prometheus:
      serviceMonitor:
        create: false # TODO: enable metrics

  valuesFrom:
    - kind: Secret
      name: secret-helm-values # created in overlay
