resources:
    # TODO: move to Database.kinda.rocks CRD
  - apiVersion: kci.rocks/v1beta1
    kind: Database
    metadata:
      name: authentik
    spec:
      deletionProtected: true
      instance: pg-instance-prod
      secretName: authentik-db-credentials
      secretsTemplates:
        # https://goauthentik.io/docs/installation/configuration#postgresql-settings
        AUTHENTIK_POSTGRESQL__HOST: "{{ .DatabaseHost }}"
        AUTHENTIK_POSTGRESQL__NAME: "{{ .DatabaseName }}"
        AUTHENTIK_POSTGRESQL__USER: "{{ .UserName }}"
        AUTHENTIK_POSTGRESQL__PORT: "{{ .DatabasePort }}"
        AUTHENTIK_POSTGRESQL__PASSWORD: "{{ .Password }}"
        AUTHENTIK_POSTGRESQL__USE_PGBOUNCER: "false"
