# https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: static-websites
resources:
  - namespace.yaml
  - ../../bases/static-websites/

patches:
  - path: websites.yaml
