apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: s3-website-gateway
spec:
  values:
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        traefik.ingress.kubernetes.io/router.entrypoints: websecure

    websites:
      - name: www-old
        hostname: www-old.cubieserver.de
        bucket: www-cubieserver-de
        endpoint: https://s3.cubieserver.de
      - name: jacks-blog
        hostname: blog.cubieserver.de
        bucket: blog-cubieserver-de
        endpoint: https://s3.cubieserver.de
      - name: adeles-blog
        hostname: adeles.cooking
        bucket: adele
        endpoint: https://s3.cubieserver.de
