apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: db-operator
spec:
  interval: 5m
  chart:
    spec:
      # https://github.com/kloeckner-i/charts/releases
      # https://github.com/kloeckner-i/db-operator/releases
      chart: "db-operator"
      version: "1.7.0"
      sourceRef:
        kind: HelmRepository
        name: kloeckneri

  # https://github.com/kloeckner-i/charts/blob/main/charts/db-operator/values.yaml
  values:
    crds:
      install: true
      keep: true

    # watch all namespaces
    watchNamespace: ""

    security:
      runAsUser: 1000
      fsGroup: 1000

    serviceMonitor:
      enabled: false

    webhook:
      # how does tekton create a webhook without requiring certificate?
      certificate:
        create: true
        issuer:
          create: false
          kind: ClusterIssuer
          name: selfsigned
