# https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ejabberd
resources:
  - namespace.yaml
  - ../../bases/ejabberd/
  - values.secret.yaml

patches:
  - target:
      kind: HelmRelease
      name: ejabberd
    patch: |-
      - op: replace
        path: /spec/values/certificate/issuerRef/name
        value: letsencrypt-production
