apiVersion: v1
kind: Secret
metadata:
    name: secret-helm-values
stringData:
    values.yaml: ENC[AES256_GCM,data:U1vNOogTA6EJh2E5SJ33tHY8NtEmjzoMGjx+eP/OmgS05n0VtW3KMrAY4a+rdSn4vl48lFZ0UFHp55urHQYiwn1SnRTbspxJNwW0XjamxdyiDatJbOBujxUYWyx+ztPojEks08NKMtlDy4igi4nEiKV+pwQJ3B4sK8bokbDkaSHAdrHECxGBes93Z3ZW2bekLXsrNwxWNALgvWRFx/Omsv3WrHIx7NafibppaOx+6HY7tnqgJd12DPTYwxvB4Vu149Qn1IyBlqlAgmDxOS58QF++QsIeZkQDjAU1PnN59j9FnZOzeXXBFOlBgYiMWL3UtQsvUltzEL+rMlIV2O5QlmQHh45o55K/hyjPhwvFyu6IAf4qQ0InY3Hio0yLQau6NTFNrMy/DDuWEkr33HL4DgeSkeuK9Ji2J+THO/n8I17dRa1au9YbOEwSrjOFy65ARU2Z6UO4+HRdFco04xl00FFvpcgNpQyI1U16IOP0pnC5EkCeOT/hvGN9B0Bzr0iL3gP/0eXt4hiOa1Caqrvan0RR+aNV67BjC8LmMBOKJSi/R5euj/7GGCTmQFatpscU44VszrkFflmEBJ0TWEsX5VdAjq/8048oP4WKkjg7SvkOSa4XtJesRURUa/PRG7DJa5XRIy0ZajTmWzoN7hgB0sXKKi+dbD63ILMDB6JAnu4hdRn2MppoWcpVTNJTPUPFtU7kSJb3/u/bAcZxSvdVCKoRSZ4kDPR7Uub/i7u4Lusl7w2E94DNaemMho2581qphlttdE5492+dbLrr4noIMc/pms35SaMTVlvsCJMjaAEfOYPGLPCc+5ktmX3vxWd6zgMv8LzDjEIRTHPBgEbYXRyybuAQn4aI8gHmQv+kw/xxoubeAODHF7FZ2bU6EneaAoGVB+oLHHB9R/9tOAsjvlxQASeFweT09ddcLr6l6ESJrXrCRFcjCb+iDXip4JUUiUvJtezI56XbMf+XeuyDysVr/cDl0+XgrS2TZz3aVtQIJgmAQ9tDv8K1d3tJPWapIEDxXY9/nsB5Zr42X36KYsZhkfDcaHcrs76Hz639UcqpEyW7zXwcT0gx2kr31SdJ4lk/mBARt1wTr0fm9unVmR5tDL5/wUOBq6I7zkoYGmyvyaemEVatWpyxllZvoU2HDjnyzDhP22ji7HRI+q+RWBQIc9zk8TMVIr8nfjiF5QzhYZyTXtCvuZXUzRtbBJhHGa3qMruIVYB2RmBDuma6aUVgpBN8TP+svHYkZIiU8mP36FBOfG3yDxGj2MEhIS6b1naggGhPiaOnseY/B02HEQa9LIRlK9J0xPEaDAQFqwWdR/PbtXWqImjyte/uIhivBZDalIv5yYCUjKnFN03h8DDHHVeHNNql6NKfyGHS8mstmV/B0t8xgLBMWCpusG+w4pVwDXH2J8vPga/b2jSbD+Q3LBjhF3IdkFbGw9nr/fsnIGE12ue2fKPeonShUZ8KNyyiQXS+WpBYPefwczDmGfI3RTnl+SUUSKT2AsHYmAVMOIOXuGBOKMBV4lWIdpqzQLmi7mNmAC7wnUOX68wVB+l97VPc/O38Dehv7Ex0zkql7AdJ5xuZ5gqG+Uo0NCLF2PiByIlii49W5x0eRu0hluG4jmccndJ5my9a3wNcmsrObOPp4IG35dxgw+pf2I8Twub5tA1Wya3Z8bMfmmWwHVHkt6E9fGFR4XEFNk8EhxSSbuC5ypW/Rnbht+Xl0c10EOOgObuXieUCNArJ5x0kNLxYFbzxOXKNE606YCHm1w==,iv:YuotNB9YzQdMqloK5nx6YSN3vQ6KDgzAFUgVwRRiXjU=,tag:F1O/s3u6WogTlVMa3WuOmQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lk9rqgq9kls8u08vadgc8pq2vwamrjkgzn3ekvthlmfffh4akflsauata6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIdDBVWHVlbWM2V1dzYjVM
            bmw0b0Y3bHdINkNPc1B3Y25KSUdWbDJDTVNjClBGNXJuSXE5VWhqNU9tZDl4dzRx
            NUFRcHVGaGZuR3BycHlaaEVDTVJNeVkKLS0tIDNsTWtsNGkyYUZUTlpKL1loU094
            ZVBrb1ZORHFVZlB4WmRxRTN6VjZYK28KXwWlDHTreSxtCJBxIZvX0WvVMpQjovkb
            MkcO79A8bXeZeWMODvGY8JB+GzWofgP1oUe1gBz58UyIXKO9ea6VNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-25T12:04:04Z"
    mac: ENC[AES256_GCM,data:3sbeZEMBoqYToDxoREKKSl3hs27qyHKH87TNt7bHr0uqaTJgDKMMlHPgO9hRTCSNckqb0evAf+KjTL+T3/FpoKWyIp8je3x3LmuzZ7c7QWHTQQi1ZPuYvUyQaQxDXqHUc13cK/O0d0CnarsTKbARs4eytWtp2XhvhiiQNh6NcQk=,iv:WpPg/5G58+nPcOdZBVGHaNs4owr56TCXM0CBlrHG6AQ=,tag:lyoF5ys1kNfUjLclIOf55w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
