- name: Install basic system utilities
  hosts: "debian"
  tasks:
    - name: Install basic system utilities
      ansible.builtin.apt:
        name:
          - nload
          - iotop
          - htop
          - nano
          - curl
          - psmisc # killall, pgrep etc.
        state: present
        update_cache: true

# TODO: Take periodic snapshots of root filesystem with "snapper"

- name: Install powermode.sh script
  hosts: "*"
  tasks:
    - name: Install powermode.sh script
      ansible.builtin.copy:
        src: files/powermode.sh
        dest: /usr/local/bin/powermode.sh
        owner: root
        group: root
        mode: '0754'
    - name: Install dependencies
      ansible.builtin.apt:
        name:
          - cpufrequtils
        state: present

# TODO: Take periodic snapshots of root filesystem with "snapper"
