- name: Install basic system utilities
  hosts: "debian"
  tasks:
    - name: Install basic system utilities
      ansible.builtin.apt:
        name:
          - btrfs-compsize
          - curl
          - htop
          - iotop
          - jq
          - lm-sensors
          - nano
          - nload
          - psmisc # killall, pgrep etc.
          - rsync
          - strace
          - xfsprogs
        state: present
        update_cache: true

    - name: Install unattended-upgrades
      ansible.builtin.apt:
        name:
          - unattended-upgrades
          - apt-listchanges
        state: present

# TODO: set up email config on the host
# https://wiki.debian.org/UnattendedUpgrades

# TODO: Take periodic snapshots of root filesystem with "snapper"

- name: Install powermode.sh script
  hosts: "*"
  tasks:
    - name: Install powermode.sh script
      ansible.builtin.copy:
        src: files/powermode.sh
        dest: /usr/local/bin/powermode.sh
        owner: root
        group: root
        mode: '0754'
    - name: Install dependencies
      ansible.builtin.apt:
        name:
          - cpufrequtils
        state: present

# TODO: Take periodic snapshots of root filesystem with "snapper"
