- name: Install basic system utilities [debian]
  hosts: "debian"
  tasks:
    - name: Install basic system utilities
      ansible.builtin.apt:
        name:
          - btrfs-compsize
          - curl
          - htop
          - iotop
          - jq
          - lm-sensors
          - nano
          - nload
          - psmisc # killall, pgrep etc.
          - rsync
          - smartmontools # for smartctl
          - strace
          - sqlite3
        state: present
        update_cache: true

    - name: Install unattended-upgrades
      ansible.builtin.apt:
        name:
          - unattended-upgrades
          - apt-listchanges
        state: present
      # TODO: set up email config on the host
      # https://wiki.debian.org/UnattendedUpgrades

- name: Install Mac CLI utilities [mac]
  hosts: mac
  connection: local
  tasks:
    - ansible.builtin.homebrew:
        name:
          - ansible
          - ansible-language-server
          - age # for file encryption
          - crane # container images
          - curl
          - editorconfig # for Emacs
          - fish
          - font-hack # for Emacs
          - git
          - go
          - gopls
          - gron # flatten JSON to make it greppable
          - helm
          - ispell # for Emacs
          - kopia
          - kubectl
          - ncdu
          - nmap
          - openshift-cli
          - python3
          - rclone
          - restic
          - rip2 # rm-improved
          - ripgrep
          - rsync
          - up # ultimate plumber, interactive pipe builder
          - sops # for file encryption
          - sqlite3
          - sshuttle # for Dev
          - yq # for Dev
        state: present

- name: Install Mac apps
  hosts: mac
  connection: local
  tasks:
    - ansible.builtin.homebrew_cask:
        name:
          - emacs
          - maccy # clipboard manager
          - nextcloud
          - podman-desktop
          - vlc

# TODO: Take periodic snapshots of root filesystem with "snapper"

- name: Install powermode.sh script [linux]
  hosts: linux
  tasks:
    - name: Install powermode.sh script
      ansible.builtin.copy:
        src: files/powermode.sh
        dest: /usr/local/bin/powermode.sh
        owner: root
        group: root
        mode: '0754'
    - name: Install dependencies
      ansible.builtin.apt:
        name:
          - cpufrequtils
        state: present
