# https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nextcloud
resources:
  - namespace.yaml
  - ../../bases/nextcloud/
  - values.secret.yaml

patches:
  - target:
      kind: Database
      name: nextcloud
    patch: |-
      - op: replace
        path: /spec/instance
        value: "mariadb-instance-prod"
      - op: replace
        path: /spec/deletionProtected
        value: true
