apiVersion: v1
kind: Secret
metadata:
    name: secret-helm-values
stringData:
    values.yaml: ENC[AES256_GCM,data:jMID97xow332fVv6xnMUG+jIoSUTyxA5g3Y9jJ9kqOorPGzV6cm1+A3PVOftCnknqpHujTU4akui69HVXQAYorOsmWcFiakbC5Q3VEmF4dUtdcEa/jBBTp94bZ6ema++LInMZg9LApjEGSimOIImJ8VQ0WynbSPVI79kFcdWFFiUn0MMC9sJskRiQETXv7tX0Bgrz3VJqtE2DQOi//KyMtHCPetps5Sp8jwDyh5iN3kiBuhhZmvBSxzLiu0ZepkhU1cqdbFOIqbB+0+j2kgKTuDFGVhyvBQnVZeaVttcHdzbCHJfhhSDwh7871N3d5mSTCjGVfZEMgCiVeap8rvt+Oy0NOCM8sfRJJH1QvhUK0hJe2T9OALNcXq0wvGjPxSrcOtpgQyuj7jq8MnP+la2iDHxc+Q3F8GBcHc7bQCzlH18lHW2FYosvgw7aS2k3kbSvn2VfV+T1O9jxjwIHNvYWAe7snp50h1+VoMMtVMsGpyYiCvyCwUxMEF9WTM5K/lujtwdaooDxACWPcI7eKqI11Yo+APLYgPBCxUA0hkrIrXRhQ==,iv:27M/gXe0pSeWMCYrO6Xpscnn+3wezkvnjvKUsNZQaO8=,tag:BQMDQohSfYlschiSe6azcA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lk9rqgq9kls8u08vadgc8pq2vwamrjkgzn3ekvthlmfffh4akflsauata6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBcDZDMzZCNWZrV2JFdERt
            cGpMeStOK3FzZDl4b2JUbmtXak03a0ZLVFFvCkJhR21VcUVIVHZuMlF4bE92NkVi
            SEFOdVVkL1JhR0x1WFdEQ3NQa21rU0kKLS0tIFc4QnFyNVhPN2gyODJ3YzlydG5a
            SCtTU1FvN3cycVRyYXdwcVdLbGhTN2sKqvw1IE6kk0C4ojKtIT3nVP4bMRsj0GJa
            0G6m5bdfinpX0FKU985ZgxxyOIo+8tPFuEAq8WN3EorNTyXbpwDFIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-29T20:59:15Z"
    mac: ENC[AES256_GCM,data:becifG2jqDfDyWgrBikXcsuhwNuAFfQqjXK2SDHywGBjmqqnMRrZy6WqJusxicQSv1AASazYM7UKDxE3XNIabkcd9R9Nk4mAim06y1yum5NkwGlTa8HiwxedTtO0swiaXLb+5PMHnwtXsz5u4KmHbwjI0mfMrg/t8/VUFpfYb3Y=,iv:TlwwNkFey8nEhnS8hlj7G7GskfleXKCxhoJwaAzTQAY=,tag:5jwgOh1SR/4MlpMokOmgtQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
