image:
  # https://hub.docker.com/r/bitnami/mariadb/tags
  tag: "11.4.4"
  # IMPORTANT: check Nextcloud supported versions!
  # https://docs.nextcloud.com/server/latest/admin_manual/installation/system_requirements.html
auth:
  # "rootPassword" set in secret values.yaml
# sleep infinity + disable health probes
# diagnosticMode:
#   enabled: true
primary:
  service:
    type: ClusterIP
  persistence:
    storageClass: local-path-xfs
    size: "1"
    annotations:
      # backups are handled with mysqldump for consistency
      # (which is not guaranteed with filesystem-level backups)
      backup-enabled: "false"

  # customize resource allocations
  resourcesPresets: none
  resources:
    requests:
      cpu: 250m
      memory: 250Mi
    limits:
      cpu: 1
      memory: 1Gi

  # Do not create a PodDisruptionBudget
  pdb:
    create: false

networkPolicy:
  enabled: true
  # do not allow outgoing connections (except cluster services, DNS etc.)
  allowExternalEgress: false
  # deny all ingress except matching pods
  # disable the value below for debugging
  allowExternal: false
  ingressNSPodMatchLabels:
    networkpolicy-mariadb-access: "enabled"
  # Unfortunately it is not easy to manage Namespace labels with Helm, therefore these labels have to be added manually to the relevant namespace.
  ingressNSMatchLabels:
    networkpolicy-mariadb-access: "enabled"

extraDeploy:
- apiVersion: kinda.rocks/v1beta1
  kind: DbInstance
  metadata:
    name: mariadb-instance-prod
    # cluster-wide resource, no namespace
  spec:
    adminSecretRef:
      # TODO: this secret should be managed by Helm as well
      Name: mariadb-admin-secret-for-db-instance
      Namespace: mariadb
    engine: mysql
    generic:
      host: mariadb.mariadb.svc.cluster.local
      port: 3306
    monitoring:
      enabled: false
    sslConnection:
      enabled: false
