# https://github.com/kloeckner-i/db-operator/blob/master/docs/creatinginstances.md
apiVersion: kci.rocks/v1beta1
kind: DbInstance
metadata:
  name: mariadb-instance-prod
  # cluster-scoped resource without namespace
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  engine: mysql
  generic:
    host: mariadb.mariadb.svc.cluster.local
    port: 3306
  adminSecretRef:
    Name: mariadb-admin-secret-for-db-instance
    Namespace: mariadb
  backup:
    bucket: ""
  monitoring:
    enabled: false
  sslConnection:
    enabled: false
    skip-verify: false
