# https://github.com/pajikos/home-assistant-helm-chart/blob/main/charts/home-assistant/values.yaml

image:
  # https://github.com/home-assistant/core/releases
  # https://github.com/home-assistant/core/pkgs/container/home-assistant
  repository: "ghcr.io/home-assistant/home-assistant"
  tag: "2026.9.3"
env:
- name: "TZ"
  value: "Europe/Zurich"
nodeSelector:
  device: zigbee-hub
# Required to use auto-discovery feature of Home Assistant
hostNetwork: true
hostPort:
  enabled: true
  port: 8123
ingress:
  # Enable ingress for home assistant
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  hosts:
    - host: home.cubieserver.de
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
   - secretName: homeassistant-ingress-cert
     hosts:
       - home.cubieserver.de
persistence:
  enabled: true
  size: 1
  storageClass: "local-path-btrfs"
additionalVolumes:
- name: homelab-toolbox
  image:
    reference: docker.io/jacksgt/homelab-toolbox:latest
    pullPolicy: Always
- name: zigbee-hub
  hostPath:
    type: CharDevice
    path: "/dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20231008100925-if00"
additionalMounts:
- name: home-assistant
  mountPath: /media/local-pvc
  subPath: media
# - name: custom-components
#   mountPath: /config/custom_components
- name: zigbee-hub
  mountPath: "/dev/ttyACM0"
- name: homelab-toolbox
  mountPath: /opt/
securityContext:
  privileged: true # required to mount a device

# additional RBAC to allow home-assistant to run specific kubectl commands
raw:
  resources:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: home-assistant-kubectl
    rules:
    - apiGroups:
      - apps
      resources:
      - deployments
      verbs:
      - get
      - list
    - apiGroups:
      - apps
      resources:
      - deployments/scale
      verbs:
      - update
      - patch
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: home-assistant-kubectl
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: home-assistant-kubectl
    subjects:
    # ServiceAccount created by main Helm chart
    - kind: ServiceAccount
      name: home-assistant
      namespace: home-assistant
