image:
  # https://github.com/gethomepage/homepage/releases
  repository: ghcr.io/gethomepage/homepage
  tag: v1.4.0
enableRbac: true
env:
  - name: HOMEPAGE_ALLOWED_HOSTS
    value: www.cubieserver.de
serviceAccount:
  create: true
resources:
  requests:
    memory: 100Mi
    cpu: 10m
  limits:
    memory: 250Mi
    cpu: 250m

securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities: { drop: ["ALL"] }

ingress:
  main:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts:
    - host: www.cubieserver.de
      paths:
      - path: /
        pathType: Prefix
    tls:
    - hosts:
      - www.cubieserver.de
      secretName: homepage-ingress-secret


# config files passed to homepage application
# https://gethomepage.dev/en/configs/services/
config:
  # https://gethomepage.dev/en/configs/kubernetes/
  kubernetes:
    mode: cluster # use serviceaccount from container

  # https://gethomepage.dev/en/configs/settings
  settings:
    title: "Cubieserver.de - Jack's Homelab"

    # https://unsplash.com/photos/XKEObIMh0V0
    background: "https://images.unsplash.com/photo-1506781994843-d2c500b1dde1?auto=format&fit=crop&w=2560&q=80"
    backgroundOpacity: 0.4
    color: zinc

    headerStyle: boxed

    hideVersion: true

    layout:
      - "Web services":
          style: row
          columns: 2
      - "Backend services":
          style: row
          columns: 2

  # https://gethomepage.dev/en/configs/bookmarks
  bookmarks:
    - Links:
      - "Jack's Blog":
        - abbr: JH
          href: https://blog.cubieserver.de
      - "Homelab Git repository":
        - abbr: HL
          href: https://git.cubieserver.de/cubieserver/homelab
      # - "Status Page":
      #   - abbr: SP
      #     href: https://status.cubieserver.de

  # https://gethomepage.dev/en/configs/services
  # Icons from https://github.com/walkxcode/dashboard-icons are supported
  services:
    - "Web services":
        - Nextcloud:
            href: https://cloud.cubieserver.de
            icon: nextcloud.png
            description: Platform for online file sharing, pictures, contacts, calendar and more
            namespace: nextcloud
            app: nextcloud
        - Authentik:
            href: https://auth.cubieserver.de
            icon: authentik.png
            description: Account management & Authentication
            namespace: authentik
            app: authentik
        - Gitea:
            href: https://git.cubieserver.de
            icon: gitea.png
            description: Git repository service
            namespace: gitea
            app: gitea
        - Jellyfin:
            href: https://media.cubieserver.de
            icon: jellyfin.png
            description: Media server for movies and TV shows
            namespace: jellyfin
            app: jellyfin
        - Stirling PDF Tools:
            href: https://pdftools.cubieserver.de
            icon: https://raw.githubusercontent.com/Frooodle/Stirling-PDF/main/docs/stirling.png
            description: Online editor for PDF documents
            namespace: stirling-pdf
            app: stirling-pdf-chart
        - U9K:
            href: https://u9k.de
            icon: https://u9k.de/static/icons/favicon-180x180.png
            description: Short URL and file sharing service
            namespace: u9k
            app: u9k
        - Redlib:
            href: https://reddit.cubieserver.de
            icon: https://raw.githubusercontent.com/redlib-org/redlib/refs/heads/main/static/logo.png
            description: Alternative frontend for Reddit
            namespace: reddit
            app: redlib
        - Rustpad:
            href: https://notepad.cubieserver.de
            icon: mdi-pencil-#ffffff
            description: Collaborative online text editor
            namespace: webtools
            app: webtools
            podSelector: >-
              app.kubernetes.io/component in (rustpad)
        - IT-Tools:
            href: https://it-tools.cubieserver.de
            icon: https://raw.githubusercontent.com/CorentinTh/it-tools/refs/heads/main/public/android-chrome-192x192.png
            description: Useful web tools for developer and people working in IT
            namespace: webtools
            app: webtools
            podSelector: >-
              app.kubernetes.io/component in (it-tools)
        - CyberChef:
            href: https://cyberchef.cubieserver.de
            icon: https://raw.githubusercontent.com/gchq/CyberChef/refs/heads/master/src/web/static/images/logo/cyberchef_hat_512.png
            description: Web app for encryption, encoding, compression and data analysis
            namespace: webtools
            app: webtools
            podSelector: >-
              app.kubernetes.io/component in (cyberchef)


    - "Backend services":
        - ejabberd:
            icon: mdi-xmpp
            description: XMPP messaging server
            namespace: ejabberd
            app: ejabberd
        - Minio:
            href: https://console-s3.cubieserver.de
            icon: minio.png
            description: S3 blob storage
            namespace: minio
            app: minio
        - Traefik:
            icon: traefik.png
            description: HTTP proxy and router
            namespace: traefik
            app: traefik
        - PostgreSQL:
            icon: postgres.png
            description: Postgres relational database
            namespace: postgres
            app: postgresql
        - MariaDB:
            icon: mariadb.png
            description: MySQL-compatible SQL database
            namespace: mariadb
            app: mariadb
        - k3s:
            icon: https://k3s.io/img/k3s-logo-light.svg
            description: Kubernetes cluster



  # https://gethomepage.dev/en/configs/widgets
  widgets:
    - greeting:
        text_size: 2xl
        text: "Jack's Homelab"

    - search:
        provider: duckduckgo
        target: _self

    # show the kubernetes widget, with the cluster summary and individual nodes
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: false
          label: "cluster"
        nodes:
          show: false
          cpu: false
          memory: false
          showLabel: false
