apiVersion: v1
kind: Service
metadata:
  name: {{ include "s3-website-gateway.fullname" . }}
  labels:
    {{- include "s3-website-gateway.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "s3-website-gateway.selectorLabels" . | nindent 4 }}
