apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "s3-website-gateway.fullname" . }}
  labels:
    {{- include "s3-website-gateway.labels" . | nindent 4 }}
automountServiceAccountToken: false
