image:
  # https://github.com/orgs/nginxinc/packages/container/package/nginx-unprivileged
  repository: ghcr.io/nginxinc/nginx-unprivileged
  tag: "1.27.4"
ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
resources:
  limits:
    cpu: 1
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi
websites:
- name: www-old
  bucket: www-cubieserver-de
  endpoint: http://minio.minio.svc.cluster.local.:9000
  hostname: www-old.cubieserver.de
- name: jacks-blog
  bucket: blog-cubieserver-de
  endpoint: http://minio.minio.svc.cluster.local.:9000
  hostname: blog.cubieserver.de
- name: jacks-blog-test
  bucket: blog-cubieserver-de-test
  endpoint: http://minio.minio.svc.cluster.local.:9000
  hostname: test-blog.cubieserver.de
- name: adeles-blog
  bucket: adele
  endpoint: http://minio.minio.svc.cluster.local.:9000
  hostname: adeles.cooking
