apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: homepage
spec:
  values:
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
        hosts:
        - host: www.cubieserver.de
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - www.cubieserver.de
          secretName: homepage-ingress-secret
