# https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homepage
resources:
  - namespace.yaml
  - ../../bases/homepage/

patches:
  - path: ingress-hostname.yaml
